name: easy_connect
description: A Flutter package for making api requests easy to use and simple including bearer token authentication.
version: 1.0.2
homepage: https://github.com/persianfluttercommunity/easy_connect

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
